# Makefile for Docker Postgres

postgres-init:
	docker run --name postgres15 -p 5433:5432 \
	-e POSTGRES_USER=postgres \
	-e POSTGRES_PASSWORD=postgres \
	-d postgres:15-alpine

postgres:
	docker exec -it postgres15 psql -U postgres

createdb:
	docker exec -it postgres15 createdb --username=postgres --owner=postgres gochat

dropdb:
	docker exec -it postgres15 dropdb --username=postgres gochat

.PHONY: postgres-init postgres createdb dropdb